# -*- coding: utf-8 -*-
"""ClipTheLandscape - Geograph Processor - v1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yArUW04Q-wZAoEiv6SsjWuf3K0d7yx-c
"""

import sys

# Geograph expects the encoded embeddings in little endian format. If using a diffente system please contact us about how to provide data
assert(sys.byteorder == 'little') # noqa: E402

import os
import torch
import clip
import requests
import time

from PIL import Image
import base64
from tqdm import tqdm
import logging

from torch import nn

#device = "cuda" if torch.cuda.is_available() else "cpu"
device = "cpu" # cuda is not supported (clip may produce float16 vectors, but geograph + clipthelandscape expect float32)

fetch_url = "https://www.geograph.org.uk/_scripts/labeler.json.php?model=clip"  #&limit=200
# clip is the short name used by geograph for "mlp-img-txt-mixup" (its the first
# clip model used!) If run tests on a different head model, then will have to
# use a different short name (contact us for details)

## Model Source: https://github.com/SpaceTimeLab/ClipTheLandscape/

## NOTE: this workbook, does NOT include location encoding. should NOT be used (as is!)
# with any of the 'with location' models.

# This is the model that decided to use:
head_name = "mlp-img-txt-mixup.pth"
head_model_url = "https://github.com/SpaceTimeLab/ClipTheLandscape/raw/refs/heads/main/heads/mlp-img-txt-mixup.pth"

# these are hardcoded, beucase need to match the data the model was trained on
clip_model = "ViT-B/32"
num_labels= 49  #could be len(tags_human)
tags_human = ["Energy infrastructure", "Coastal", "Lowlands", "Geological interest", "Historic sites and artefacts", "Uplands", "Paths", "Boundary, Barrier", "Sport, Leisure", "Farm, Fishery, Market Gardening", "Grassland", "Rivers, Streams, Drainage", "Village, Rural settlement", "Housing, Dwellings", "Public buildings and spaces", "Religious sites", "Quarrying, Mining", "Park and Public Gardens", "Business, Retail, Services", "Lakes, Wetland, Bog", "Suburb, Urban fringe", "Educational sites", "Wild Animals, Plants and Mushrooms", "Islands", "Roads, Road transport", "Air transport", "Country estates", "City, Town centre", "Railways", "Derelict, Disused", "Health and social services", "Construction, Development", "People, Events", "Burial ground, Crematorium", "Woodland, Forest", "Industry", "Communications", "Water resources", "Air, Sky, Weather", "Waste, Waste management", "Heath, Scrub", "Canals", "Docks, Harbours", "Defence, Military", "Flat landscapes", "Estuary, Marine", "Moorland", "Rocks, Scree, Cliffs", "Barren Plateaux"]
# These are the tags in the exact same order as used by the model

# temporay folder to hold downloaded files, will be created if needed (automatically cleared)
image_dir = 'tmp'
sleep = 1
log_file = 'processing.log'

os.makedirs('heads', exist_ok=True)

if not os.path.exists('heads/'+head_name):
  # Only need to fetch the heads file we need...
  response = requests.get(head_model_url)
  with open('heads/'+head_name, 'wb') as f:
    f.write(response.content)

########################################

import hashlib
import random
import socket

def get_instance_identifier():
    # --- Kubernetes Environment ---
    pod_uid = os.environ.get('KUBERNETES_POD_UID')
    if pod_uid:
        return f"k8s-uid-{pod_uid}"

    pod_name = os.environ.get('KUBERNETES_POD_NAME')
    if pod_name:
        return f"k8s-pod-{pod_name}"

    # --- Jupyter/Colab Environment ---
    colab_notebook_id = os.environ.get('COLAB_NOTEBOOK_ID')
    if colab_notebook_id:
        return f"colab-{colab_notebook_id}"

    jpy_session_name = os.environ.get('JPY_SESSION_NAME')
    if jpy_session_name:
        return f"jupyter-{jpy_session_name}"

    # --- Docker Environment --- (and in fact will work with Kubernetes, if dont have those variables (ours doesnt!)
    try:
        container_hostname = socket.gethostname()
        # Check if it looks like a typical Docker short ID (12 hex chars) or a name
        # A name will usually be more descriptive, an ID is 12 hex chars
        if len(container_hostname) == 12 and all(c in '0123456789abcdef' for c in container_hostname.lower()):
            return f"docker-id-{container_hostname}"
        elif container_hostname:
            return f"docker-name-{container_hostname}"
    except Exception as e:
        logging.warning(f"Could not get hostname from socket: {e}")

    # --- Fallback: Random Identifier ---
    random_id = ''.join(random.choices('0123456789abcdef', k=16))
    return f"random-{random_id}"

hashed_identifier = hashlib.sha256(get_instance_identifier().encode()).hexdigest()
unique_number = int(hashed_identifier, 16) % 32

print(f"Using stable unique number: {unique_number}")

########################################

print(device)
print(clip.available_models())

model, preprocess = clip.load(clip_model, device=device)

# Preload the Selected Model
########################################
# Code extracted from https://github.com/SpaceTimeLab/ClipTheLandscape/

use_img = 'img' in head_name
use_txt = 'txt' in head_name
use_loc = 'loc' in head_name

# Calculate classifier input dimension
input_dim = sum([
    512 if use_img else 0,
    512 if use_txt else 0,
    2 if use_loc else 0
])

# Set up head architecture
if head_name.split('-')[0] == 'mlp':
    head = nn.Sequential(
        nn.Linear(input_dim, 256),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(256, num_labels)
    ).to(device)
elif head_name.split('-')[0] == 'linear':
    head = nn.Linear(input_dim, num_labels).to(device)
else:
    print(f'Cannot build {head_name}.')

# Load model params
head.load_state_dict(
    torch.load(
        f'heads/{head_name}',
        map_location=device
    )
)

head.eval()

# useful function

def post_with_retries(url, json_data, attempts=3, delay=2):
    for i in range(1, attempts + 1):
        try:
            res = requests.post(url, json=json_data, timeout=10)
            res.raise_for_status()
            #print(f"Success on attempt {i}.")
            return res
        except requests.exceptions.RequestException as e:
            print(f"Attempt {i} failed: {e}. Retrying...") if i < attempts else print(f"Attempt {i} failed: {e}. Max retries reached.")
            if i < attempts:
                time.sleep(delay)
    raise requests.exceptions.RequestException(f"Failed after {attempts} attempts.") # Re-raise if all fail

os.makedirs(image_dir, exist_ok=True)

# Configure logging
logging.basicConfig(filename=log_file, level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s')

def get_env_int(name, default, warn=True):
    value_str = os.environ.get(name)
    if value_str is None:
        return default

    try:
        return int(value_str)
    except ValueError:
        if warn:
            print(f"Warning: '{name}' environment variable '{value_str}' is not a valid integer. Using default value of {default}.")
        return default

loops = get_env_int('LOOPS', 100)
batch = get_env_int('BATCH', 250)

for loop in range(loops):
    ##############################
    # Fetch Data

    params = {
        "limit": batch, #defines the largest you want, might get smaller batches.
        "unique_number": unique_number
    }

    logging.info(f'Starting Loop #{loop}')
    try:
        response = requests.get(fetch_url, params=params)
        response.raise_for_status()
        data_json = response.json() #has built in json decoder

        if not data_json or 'rows' not in data_json or not data_json['rows']:
            logging.warning("No rows returned from the server. Waiting before retrying.")
            print("No rows returned from the server. Waiting before retrying.")
            if "sleep" in data_json:
                sleep = data_json['sleep']
            else:
                sleep = sleep * 2 # implement expentional backoff!
            time.sleep(sleep)
            continue

        logging.info(f"Fetched data for {len(data_json['rows'])} Images, first ID: {data_json['rows'][0]['gridimage_id']}")
        print(f"Fetched data for {len(data_json['rows'])} Images, first ID: {data_json['rows'][0]['gridimage_id']}")

    except (requests.exceptions.HTTPError, requests.exceptions.JSONDecodeError) as e:
        logging.error(f'Failed. error code - {e}.')
        sleep = sleep * 2 # implement expentional backoff!
        time.sleep(sleep)
        continue

    if "sleep" in data_json:
        sleep = data_json['sleep']

    #wait a bit if nothing to process
    if not data_json['rows']:
        time.sleep(sleep * sleep * sleep)
        continue

    ##############################
    #PreProcess images - fetch

    logging.info('Fetching Images...')

    current_image_batch = []   # will be holding preprocessed image
    current_text_batch = []    # will be holding the tokenized text
    img_embeds = []
    txt_embeds = []

    failures = []
    for image in tqdm(data_json['rows']):

        img_id = image['gridimage_id']
        filename = image_dir + '/' + os.path.basename(image["fullpath"])

        if not os.path.isfile(filename):
            fullurl = data_json['prefix'] + image['fullpath']

            logging.info(f'Fetching {fullurl}')
            try:
                with requests.get(fullurl) as file:
                    file.raise_for_status()
                    with open(filename, 'wb') as fd:
                        for chunk in file.iter_content(chunk_size=2048):
                            fd.write(chunk)

            except requests.exceptions.HTTPError as e:
                logging.error(f'Failed fetching image {fullurl}. error code - {e.response.status_code}')

        ##############################
        logging.info(f'Processing  {filename}')

        ###img = preprocess(Image.open(filename))
        try:
            # Use a 'with' statement for proper file handling (Pillow handles closing)
            # This is where Pillow might raise errors
            with Image.open(filename) as pil_img:
                # Attempt to preprocess the image
                img = preprocess(pil_img)

        except Exception as e:
            # Catch any other unexpected errors during image loading or preprocessing
            logging.error(f"An unexpected error occurred while processing image {filename}: {e}")

            failures.append({"image_id": int(image['gridimage_id']), "label": 'Failed', "score": -1 })
            continue # skip rest of precessing

        # the ClipTheLandscape model, and Geograph both expect float32 (if running on GPU clip might produce float16)
        assert img.dtype == torch.float32, "Image tensor must be torch.float32"

        current_image_batch.append(img)

        # Text tokenizer
        #ALL images have a title, so dont have to deal with missing titles
        txt_tokens = clip.tokenize([image['title']])
        current_text_batch.append(txt_tokens)

    if failures:
        # for NOW, lets just inform that it failed, and restart the main loop.
        # So we dont have to deal with partial batches. When restart the new
        # list of images wont have the failures. Any images already downloaded
        # will still be temp folder.

        try:
            with requests.post(fetch_url, json=failures) as response:
                result = response.text.replace("\n", "; ")
                logging.info(f'Failed image batch submission response: {result}')
        except requests.exceptions.RequestException as e:
            logging.error(f"Failed to submit failures: {e}")

        time.sleep(sleep)
        continue # skip rest of precessing

    logging.info(f'Done Pre Processing for #{loop}')

    ##############################
    # Process image batch
    images_tensor = torch.stack(current_image_batch).to(device)

    # Process text batch
    # Stack all tokenized tensors. Make sure they are padded to the same length!
    # clip.tokenize by default pads to the longest sequence in the batch or a fixed length (77 for CLIP)
    text_tensor = torch.cat(current_text_batch).to(device)

    logging.info('Extracting Features...')

    with torch.no_grad():
        img_embeds = model.encode_image(images_tensor).cpu().detach() # This now returns a batch of features
        txt_embeds = model.encode_text(text_tensor).cpu().detach() # This now returns a batch of features

    # the ClipTheLandscape model, and Geograph both expect float32 (if running on GPU clip might produce float16)
    assert img_embeds.dtype == torch.float32, "Image tensor must be torch.float32"

    logging.info(f'Done Embedding for #{loop}')

    ##############################
    probs = []

    with torch.no_grad():
        logging.info(f'working on {len(img_embeds)} images:')
        fused_parts = []
        if use_img:
            fused_parts.append(img_embeds)
        if use_txt:
            fused_parts.append(txt_embeds)
        #if use_loc:
        #    fused_parts.append(loc_f)

        fused = torch.cat(fused_parts, dim=1).to(device)

        probs = torch.sigmoid(head(fused)).cpu()

    logging.info(f'Done Main Processing #{loop}')

    ##preds = (probs > 0.5).int() # binarise predictions


    print(f'Processed #{loop}, submitting results...')
    ##############################
    # submit even lower scores, geograph still knows to only use score > 0.5

    logging.info(f'Submitting Labels #{loop} [{len(probs)} images]')

    final = []
    for idx, predicts in enumerate(probs):
        found = False
        for i, v in enumerate(predicts):
            if v > 0.2:
                found = True
                final.append({"image_id": int(data_json['rows'][idx]['gridimage_id']), "label": tags_human[i], "score": v.tolist() })

        #if there are no predictions, then still need to submit to flag that checked
        if not found:
            final.append({"image_id": int(data_json['rows'][idx]['gridimage_id']), "label": 'None', "score": 0})

    #json_output = json.dumps(final) #, indent=4)
    #print(json_output)

    try:
        with post_with_retries(fetch_url, final, delay=sleep) as response:
            result = response.text.replace("\n", "; ")
            logging.info(f'Label submission response: {result}')
    except requests.exceptions.RequestException as e:
        logging.error(f"Failed to submit labels: {e}")

    ##############################
    # We also submit the extracted embeddings

    logging.info(f'Submitting Embeddings #{loop} [{len(img_embeds)} images]')

    embeddings_to_send = [] # To store JSON payloads for each embedding
    for idx, embedding in enumerate(img_embeds):
        binary_embedding = embedding.numpy().tobytes()
        embeddings_to_send.append({
            "image_id": int(data_json['rows'][idx]['gridimage_id']),
            "type": "image",
            "embeddings": base64.b64encode(binary_embedding).decode('utf-8')
        })

        #logging.info(f"Image embedding preview: {embedding.numpy()[0:10]}") # Log a preview if needed

    for idx, embedding in enumerate(txt_embeds):
        binary_embedding = embedding.numpy().tobytes()
        embeddings_to_send.append({
            "image_id": int(data_json['rows'][idx]['gridimage_id']),
            "type": "title",
            "embeddings": base64.b64encode(binary_embedding).decode('utf-8')
        })
        #logging.info(f"Text embedding preview: {embedding.numpy()[0:10]}") # Log a preview if needed

    #json_output = json.dumps(embeddings_to_send, indent=4)
    #print(json_output)

    try:
        with post_with_retries(fetch_url, embeddings_to_send, delay=sleep) as response:
            result = response.text.replace("\n", "; ")
            logging.info(f'Embedding submission response: {result}')
    except requests.exceptions.RequestException as e:
        logging.error(f"Failed to submit embeddings: {e}")

    ##############################
    # delete temporary files

    if True:
        for image in data_json['rows']:
            filename = image_dir + '/' + os.path.basename(image["fullpath"])
            try:
                os.unlink(filename)
            except OSError as e:
                logging.error(f"Error deleting file {filename}: {e}")


    logging.info(f'Done #{loop}')
    ##break # one for now
    time.sleep(sleep)

print('Finished')

