name: clip-the-landscape
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - pandas=2.2.2
  - pip
  - pip:
    - torch
    - ftfy
    - regex
    - tqdm==4.66.2
    - git+https://github.com/openai/CLIP.git
    - Pillow==10.1.0
